name: .NET Org Area Pod Issue Triage
description: A GitHub action that drives the .NET org's area pod issue triage process

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

inputs:
  GITHUB_TOKEN:
    description: The GITHUB_TOKEN secret to use for connecting to GitHub APIs
    required: true
    default: ${{ github.token }}
  issue:
    description: The issue number to triage
    required: true
    type: number

runs:
  using: docker
  image: ../Dockerfile
  args: [ "--issue", "${{ inputs.issue }}" ]
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
