name: .NET Org Area Pod Issue Triage
description: A GitHub action that drives the .NET org's area pod issue triage process
inputs:
  pod:
    description: The area pod to run issue triage for
    required: true
  issue_number:
    description: The issue number to triage
    required: true

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/action-playground/areapod-issuetriage:main
  args: [ "--pod", "${{ inputs.pod }}", "--issue", "${{ inputs.issue_number }}" ]
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
