name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual run of Area Pod Issue Triage

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    container:
      image: docker://ghcr.io/jeffhandley/action-playground/areapod-issuetriage:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
