name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      dockertag:
        description: The docker image tag to use
        required: true
        default: main

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pod: ["adam/david", "buyaa/jose/steve", "akhil/carlos/viktor"]

    steps:
      - name: Area Pod Issue Triage
        uses: docker://ghcr.io/jeffhandley/action-playground/areapod-issuetriage:${{ github.event.inputs.dockertag }}
        with:
          args: --pod "{{ matrix.pod }}""