name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual testing of the Area Pod Issue Triage action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log the reason for this manual run
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Area Pod Issue Triage
        id: areapod-issuetriage
        uses: jeffhandley/action-playground/actions/AreaPod/AreaPod.IssueTriage@main
