name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      issue:
        description: Issue number
        required: true
        type: number
      actionref:
        description: Action reference
        required: true
        default: "@main"
        type: choice
        options:
        - "@main"
        - "/source@main"

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    steps:
      - name: Area Pod Issue Triage
        if: ${{ github.event.inputs.host == 'docker' }}
        uses: jeffhandley/action-playground/actions/AreaPod/AreaPod.IssueTriage${{ github.event.inputs.actionref }}
        with:
          issue: ${{ github.event.inputs.issue }}
