name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual testing of the Area Pod Issue Triage action

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/action-playground/areapod-issuetriage
  IMAGE_TAG: main

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Record the reason for this manual run
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Area Pod Issue Triage
        uses: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
