name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      dockertag:
        description: The docker image tag to use
        required: true
        default: main
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual run of Area Pod Issue Triage
      command:
        description: Command to run in the container
        required: true
        default: /actions/AreaPod.IssueTriage

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    container:
      image: docker://ghcr.io/jeffhandley/action-playground/areapod-issuetriage:${{ github.event.inputs.dockertag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Area Pod Issue Triage
        run: ${{ github.event.inputs.command }}
