name: Area Pod Issue Triage

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

on:
  workflow_dispatch:
    inputs:
      issue:
        description: Issue number
        required: true
        type: number
      action:
        description: The event action to simulate
        required: true
        type: choice
        options:
        - opened
        - closed
        - transferred
        - reopened
        - assigned
        - unassigned
        - labeled
        - unlabeled
        - milestoned
        - demilestoned
      assignee:
        description: The assignee (assigned or unassigned)
        required: false
      label:
        description: The label (labeled or unlabeled)
        required: false

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    steps:
      - name: Area Pod Issue Triage
        uses: jeffhandley/action-playground/actions/AreaPod/AreaPod.IssueTriage@main
        with:
          issue: ${{ github.event.inputs.issue }}
          action: ${{ github.event.inputs.action }}
          assignee: ${{ github.event.inputs.assignee }}
          label: ${{ github.event.inputs.label }}
