# This workflow will add labels based on issue and pull request interactions

name: Interaction Labels
on:
  issues:
    types: [opened, reopened, edited, transferred, closed]
  pull_request:
    types: [opened, reopened, edited, closed, merged]

  workflow_dispatch:
    inputs:
      event_name:
        required: true
        type: string
        default: issues
      action:
        required: true
        type: string
        default: edited    

permissions:
  issues: write
  pull-requests: write
  
jobs:
  echo_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event_name: [issues, pull_request]
        action: [opened, reopened, edited, transferred, closed]
    steps:
      - name: Echo matrix values
        run: |
          echo event_name: ${{ github.event_name }}
          echo action: ${{ github.event.action }}
          echo inputs.event_name: ${{ github.event.inputs.event_name }}
          echo inputs.action: ${{ github.event.inputs.action }}
          echo matrix.event_name: ${{ matrix.event_name }}
          echo matrix.action: ${{ matrix.interaction }}
          echo inputs or event: ${{ github.event.inputs.event_name || github.event_name }}
          echo inputs or event: ${{ github.event.inputs.action || github.event.action }}
          echo environment event_name: $event_name
          echo environment action: $action
        env:
          event_name: ${{ github.event.inputs.event_name || github.event_name }}
          action: ${{ github.event.inputs.action || github.event.action }}
