name: "Publish: areapod-issuetriage"

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./actions/AreaPod/AreaPod.IssueTriage
          file: ./actions/AreaPod/AreaPod.IssueTriage/Dockerfile
          push: false
          tags: jeffhandley/action-playground/areapod-issuetriage:latest
