name: "Publish: areapod-issuetriage"

on: workflow_dispatch

defaults:
  working-directory: ./actions/AreaPod/AreaPod.IssueTriage

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: actions/AreaPod/AreaPod.IssueTriage/Dockerfile
          context: .
          push: false
          tags: jeffhandley/action-playground/areapod-issuetriage:latest
