name: "Publish: areapod-issuetriage"

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/action-playground/areapod-issuetriage
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Log job info
        env:
          DOCKER_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          echo "Building and pushing Docker image:
          echo "  ${{ env.DOCKER_IMAGE }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./actions/AreaPod/AreaPod.IssueTriage
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
