name: "Publish: areapod-issuetriage"

on:
  workflow_dispatch:
    inputs:
      dockertag:
        description: Tag to use on the docker image
        required: true
        default: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log the event payload
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./actions/AreaPod/AreaPod.IssueTriage
          push: false
          tags: ghcr.io/jeffhandley/action-playground/areapod-issuetriage:${{ github.event.inputs.dockertag }}
