name: "Publish: areapod-issuetriage"

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: ./actions/AreaPod/AreaPod.IssueTriage
          push: false
          tags: ghcr.io/jeffhandley/action-playground/areapod-issuetriage:latest
