name: "Publish: areapod-issuetriage"

on: workflow_dispatch

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log job info
        run: |
          echo "Building and pushing Docker image with tags:"
          echo "  ghcr.io/jeffhandley/action-playground/areapod-issuetriage:${{ github.ref_name }}"

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./actions/AreaPod/AreaPod.IssueTriage
          push: true
          tags: ghcr.io/jeffhandley/action-playground/areapod-issuetriage:${{ github.ref_name }}
